#theme: jekyll-theme-minimal
remote_theme: "jekyll/minima@2.5-stable"

# Note, we are using version 2.5, so you should 
# read these instuctions, not the ones at the HEAD of the
# master branch
# https://github.com/jekyll/minima/blob/2.5-stable/README.md

title: League Labs
url: "https://labs.jointheleague.org"
baseurl: ""

description: >
  LEAGUE Labs is our unpaid internship program for High School students to
  develop new LEAGUE classes. LEAGUE Labs Interns will create 90 minute classes,
  on a subject of their choice, and teach that class to other students in our
  Tech Club or Code Clinic programs.

plugins:
  - jekyll-remote-theme

# If you don't define the nav pages here, the
# default is to use  all of the pages.
header_pages:
- teams/index.md

minima:

  social_links:
    - title: X
      icon: x-twitter
      url: https://x.com/LEAGUEofAmazing
    - title:
      icon: github
      url: https://github.com/jointheleague
    - title: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/company/4849605/
    - title: Instagram
      icon: instagram
      url: https://www.instagram.com/jointheleague/

  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized 
  skin: classic




